### ISSUE TITLE
Lookup caching

### ISSUE THREAD

**Issue by organisciak** [bmschmidt/pySRP#10]
We discussed this in the compare_tools repo, but I'm dropping in an issue here, since it may need addressing. My most recent merge of the lookup on-disk caching was in master, so we should discuss a) if you'd prefer that branched off and b) details of how it works.

Generally, the pitch is - on-disk caching will be slower than building the lookup table on demand (or saving/loading the cache to memory), but it will allow the vector_files to scale to sizes where the dictionary is too big to hold in memory, especially with multiple processes. The new prefix_lookup

I tried to keep the code separate and unintrusive. However, the import isn't optional - which you may want to do. It's a pure python library, for what it's worth, so not a tricky dependency.

**Comment by bmschmidt** [comment]
Thanks for this.

I think I'd probably rather keep the possibility for an in-memory cache, but I can implement that if I think it's necessary. 

But--this appears to [break the test suite](https://travis-ci.org/bmschmidt/pySRP/builds/657902554?utm_source=github_status&utm_medium=notification). Would you mind taking a stab at fixing that? Some output below.

======================================================================
ERROR: test_entrance_format (__main__.ReadAndWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test.py", line 55, in test_entrance_format
    f['foo']
  File "/home/bschmidt/Dropbox/SRP/libs/python/SRP/SRP_files.py", line 555, in __getitem__
    self._build_offset_lookup()
  File "/home/bschmidt/Dropbox/SRP/libs/python/SRP/SRP_files.py", line 433, in _build_offset_lookup
    if sep is None and label in self._offset_lookup:
AttributeError: 'Vector_file' object has no attribute '_offset_lookup'

======================================================================
ERROR: test_prefix_lookup (__main__.ReadAndWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test.py", line 73, in test_prefix_lookup
    fname, row = newview.find_prefix("file_100")[0]
IndexError: list index out of range

======================================================================
ERROR: test_sorting (__main__.ReadAndWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test.py", line 34, in test_sorting
    fin.sort(Path(dir, "test2.bin"))
  File "/home/bschmidt/Dropbox/SRP/libs/python/SRP/SRP_files.py", line 489, in sort
    self._build_offset_lookup()
  File "/home/bschmidt/Dropbox/SRP/libs/python/SRP/SRP_files.py", line 433, in _build_offset_lookup
    if sep is None and label in self._offset_lookup:
AttributeError: 'Vector_file' object has no attribute '_offset_lookup'

----------------------------------------------------------------------
Ran 14 tests in 0.009s

FAILED (errors=4)

**Comment by organisciak** [comment]
Definitely. I'll fix it shortly - I had thought the error was simply the
missing dependency :/

Peter

**Comment by organisciak** [comment]
Ben, I'd like to check with you about passing a test.

You have a test where you 'find_prefix', then add new data to the vector_file, then 'find_prefix' for that new data. The test passed before because the `_prefix_offset` was rebuilt every time you called it. `_build_offset_lookup` didn't have the code that only rebuilds an existing lookup `if force==True`. I broke the test by adding that test.

How would you like me to proceed?

1. To get the previous functionality, I can add add `force=True` when `find_prefix` calls `_build_offset_lookup`. I don't think that's desirable.
2. Reconsider the test case of adding to the vector file after building the lookup. Maybe that should expect a user-driven force rebuild.
3. Engineer some logic where it force rebuilds the lookup when `find_prefix` fails to find the prefix.
4. Add logic where it tries to add to the prefix_lookup (without a full rebuild) if `find_prefix` fails.

**Comment by organisciak** [comment]
I should note that #4 seems easier than it is - since we don't have it in the lookup, it still requires an iteration through the entire file to look for the vectors and if they exist. So it's essentially the same as #3, except would be quicker when using the on-disk cache.

Also:
5. - extend the lookup when `add_row` is done after a lookup dict has already been created. The file offset is available, right?
6. - Remember the last offset location when a lookup dict is created. Then we can have an 'update_offset_lookup' that iterates only through vectors adds since the last build. I like this option.

**Comment by organisciak** [comment]
I gave number 6 a try. See pull request https://github.com/bmschmidt/pySRP/pull/11.
